name: Push essentials package to artifacts

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Install required packages
        run: |
          sudo apt update
          sudo apt install curl locales-all cli-common-dev libunwind8-dev libcurl4-openssl-dev
        
      - name: Initialize offline package
        run: |
          sudo ip netns add no-net
          chmod +x initializeoffline.sh
          ./initializeoffline.sh --generate-essentials-archive
        
      - name: Upload essentials to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Essentials
          path: |
            Essentials.tar.xz
            offline/.dotnet
